### ISSUE TITLE
🧠 Logic: 📁 handle `consult/1` predicate to fetch smart contract prolog file

### ISSUE THREAD

**Issue by bdeneux** [okp4/okp4d#305]
## 📝 Purpose 

Prolog file can be handled into the chain provided by a `cw-storage` smart contract or other smart contract object provider. The `consult/1` predicate is here to fetch a prolog file from a logic ask query. 

Implement the virtual file system that will handle the `consult/1` predicate and fetch the corresponding file. File can be provided by a custom uri that will indicate where the file is located and how to fetch it. 

### 🔮 Wasm uri

Here a proposition for fetch wasm smart contract prolog file : (thank to @amimart for the proposition) 

```
okp4://wasm/{contract_address}?query={contract_query}
```

- `{contract_address}`: is the wasm contract address that will host prolog file object (e.i.: `okp415ekvz3qdter33mdnk98v8whv5qdr53yusksnfgc08xd26fpdn3ts8gddht`)
- `{contract_query}`: is the query of the smart contract that will return the binary prolog file. (e.i. for the cw-storage contract : `%7B%22object_data%22%3A%7B%22id%22%3A%20%224cbe36399aabfcc7158ee7a66cbfffa525bb0ceab33d1ff2cff08759fe0a9b05%22%7D%7D`). The query should be obviously url encoded. 

## 🎯 Exemple 

Given a Prolog file saved on the smart contract at address `okp415ekvz3qdter33mdnk98v8whv5qdr53yusksnfgc08xd26fpdn3ts8gddht` and a file id `4cbe36399aabfcc7158ee7a66cbfffa525bb0ceab33d1ff2cff08759fe0a9b05`

```prolog
calc(X) :-  X is 100 + 200.
```

When asking the logic module : 
```cli
> okp4d query logic ask "consult('okp4://wasm/okp415ekvz3qdter33mdnk98v8whv5qdr53yusksnfgc08xd26fpdn3ts8gddht?query=%7B%22object_data%22%3A%7B%22id%22%3A%20%224cbe36399aabfcc7158ee7a66cbfffa525bb0ceab33d1ff2cff08759fe0a9b05%22%7D%7D'), calc(X)."
```

Answer is 

```
answer:
  has_more: false
  results:
  - substitutions:
    - term:
        arguments: []
        name: "300"
      variable: X
  success: true
  variables:
  - X
gas_used: "69816"
height: "32875"
```
